export type {
  SpreadsheetAnchorPoint as XlsxAnchorPoint,
  SpreadsheetCell as XlsxCell,
  SpreadsheetCellStyle as XlsxCellStyle,
  SpreadsheetChart as XlsxChart,
  SpreadsheetColumn as XlsxColumn,
  SpreadsheetImage as XlsxImage,
  SpreadsheetMerge as XlsxMerge,
  SpreadsheetRow as XlsxRow,
  SpreadsheetSheet as XlsxSheet,
  SpreadsheetWorkbook as XlsxWorkbook,
} from '../spreadsheet/types';
